name: Build and Release PostgreSQL with PostGIS and pgRouting

on:
  push:
    branches:
      - master
      - feature/macos-postgis
  workflow_dispatch:

jobs:
  build-and-release:
    strategy:
      matrix:
        # pg_version: ["13.14", "14.11", "15.6", "16.2"]
        pg_version: ["13.14"]
        os: [macos-15-large, macos-15-xlarge]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build PostgreSQL, PostGIS, and Dependencies
        run: |
          ./scripts/build-postgres-darwin.sh -v ${{ matrix.pg_version }} -g 3.1.4 -r 3.2.0

      - name: Prepare Release Assets
        id: prepare_release
        run: |
          mkdir -p release
          # xlarge is arm64, and large is x86_64
          # put filename into environment variable
          if [ "${{ matrix.os }}" == "macos-15-xlarge" ]; then
            echo "ARCH=arm64" >> $GITHUB_OUTPUT
            echo "FILENAME=postgresql-${{ matrix.pg_version }}-darwin-arm64.txz" >> $GITHUB_OUTPUT
          else
            echo "ARCH=amd64" >> $GITHUB_OUTPUT
            echo "FILENAME=postgresql-${{ matrix.pg_version }}-darwin-amd64.txz" >> $GITHUB_OUTPUT
          fi
          cp bundle/postgres-macos.txz "release/$FILENAME"

      - name: Calculate SHA256 Checksums
        run: |
          cd release
          shasum -a 256 $FILENAME > SHA256SUMS.txt

      - name: Get date
        id: get_date
        run: |
          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ matrix.pg_version }}-macos-${{ steps.prepare_release.outputs.ARCH }}-${{ steps.get_date.outputs.DATE }}"
          release_name: "${{ matrix.pg_version }}-macos-${{ steps.prepare_release.outputs.ARCH }}-${{ steps.get_date.outputs.DATE }}"
          draft: false
          prerelease: false
          body: |
            SHA256 Checksums:
            ```
            $(cat release/SHA256SUMS.txt)
            ```

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/${{ steps.prepare_release.outputs.FILENAME }}
          asset_name: ${{ steps.prepare_release.outputs.FILENAME }}
          asset_content_type: application/x-tar

