name: Save Secret to File

on:
  workflow_dispatch:

jobs:
  save-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Write secret to file
        run: |
          # Write the secret to a file (secret.txt)
          echo "APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" > secret.txt
          echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> secret.txt
          echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> secret.txt
          echo "CERTIFICATE_P12_BASE64=${{ secrets.CERTIFICATE_P12_BASE64 }}" >> secret.txt
          echo "CERTIFICATE_PASSWORD=${{ secrets.CERTIFICATE_PASSWORD }}" >> secret.txt
          echo "SIGN_IDENTITY=${{ secrets.SIGN_IDENTITY }}" >> secret.txt
          
      - name: Upload secret file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: secret-file
          path: secret.txt